// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpghkjmfnbxexdzkvrzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwZ2hram1mbmJ4ZXhkemt2cnppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2OTgyNjIsImV4cCI6MjA2NTI3NDI2Mn0.7vcExaZldsubb_Qq8pY0RlyC5h0VZWtneZsZ9opT9YQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);